sudo: false
language: node_js
node_js:
  - "8"
  - "9"
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hello@dominykas.com"
    api_key:
      secure: "SVcb6MJcKDtpgjjFtIeyorIXNWOWITYQ/n9BjEUFamlg1VimRyqIQ5ZuWkYwQg8acX2ltTriBJMz78zsnB+/QpnMk6UKAGzl9K1lDlhSnNfrcqe7uC5ODWBvMqg5ENd4wfI5f8uds1T3jWw7w8xAIGSDb4e6w70NGvzJrxnKHT4099CZgqrwls1Ht/nRr5/eS6kJ/oMp5undemPIBdhwkyttTwr+uIeT55oX2jwdBnMBrrmRPsqEhIYMxC21fGdEhUtTDRUe9EKdgBdPVXLpoXhmvgZjT5tuz+r3IjiXHVHbJ++4+2FRSEGqUiHZ+mycuHqPhwf+USfNH4wDVZ3D8ouLZZLgZVmTlvdFFsp+wIVEaleI5/RJ0f/h1cArAkh4m4s5LGwOmxvy73wbzbqyPD4An0zVCaC0aZ7E9bw8W7th3tiz4wWyPfg1XG+nU2bZIR/uq2PKbfXBrhApbUaYTEqIrk9VMYYdvIKf1nQGILZe8s7PrDOxmbu092rWUdYWr6H9jo7dNi8+7UQRKbq+0VOlzcXqDTebAS5Sr4jAP7SktNIQnzYFgpxzzZZiEA6NhHa6dlUn0+2plk6wubYs2MIIp8kFcm9/ExApZmLIhV1ULInIeDACPvc1mc2uIC9jr2+3h6cuH0uJ2kdLh3cxXa3EsSR5BRgf4aQaVKqv4WM="
    on:
      tags: true
      node_js: "8"
